# -*- coding: utf-8 -*-
"""lesson_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTmQwRPq0q57v9vAaABogTAQJCfjarui
"""

# Commented out IPython magic to ensure Python compatibility.
# отключим предупреждения Anaconda  https://habr.com/ru/company/ods/blog/323210/
import warnings
warnings.simplefilter('ignore')

# будем отображать графики прямо в jupyter'e
# %matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt
#графики в svg выглядят более четкими
# %config InlineBackend.figure_format = 'svg' 

#увеличим дефолтный размер графиков
from pylab import rcParams
rcParams['figure.figsize'] = 8, 5
import pandas as pd

df = pd.read_csv('/content/Video_Games_Sales_as_at_22_Dec_2016.csv')
df.info()

useful_cols = ['Name', 'Platform', 'Year_of_Release', 'Genre', 
               'Global_Sales', 'Critic_Score', 'Critic_Count',
               'User_Score', 'User_Count', 'Rating'
              ]
df[useful_cols].head()

sales_df = df[[x for x in df.columns if 'Sales' in x] + ['Year_of_Release']]
sales_df.groupby('Year_of_Release').sum().plot()

sales_df.groupby('Year_of_Release').sum().plot(kind='bar', rot=45)

corr_matrix = df.drop(['Global_Sales'], axis=1).corr()
sns.heatmap(corr_matrix);

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd

# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/howpop_train.csv")
df.head(3).T

df.drop(
    filter(lambda c: c.endswith("_lognorm"), df.columns),
    axis=1,  # axis = 1: столбцы
    inplace=True,
)  # избавляет от необходимости сохранять датасет
df.describe().T

df.describe(include=["object", "bool"]).T  # бинарные и категориальные переменные



print(df.published.dtype)
df["published"] = pd.to_datetime(df.published, yearfirst=True)
print(df.published.dtype)

df["year"] = [d.year for d in df.published]
df["month"] = [d.month for d in df.published]

df["dayofweek"] = [d.isoweekday() for d in df.published]
df["hour"] = [d.hour for d in df.published]

df.head()

df[df['dayofweek'] == 6][ df['month'] == 3].sum().plot(kind='bar', rot=45)

df[df['author']].head()

df[df['dayofweek'] == 1].groupby('hour').sum().plot(kind='bar', rot=45)

df[df['dayofweek'] == 6]df["hour"]..sum().plot(kind='bar', rot=45)