# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18tttYrmle4-0zNEYoErqZXL6L0XfxHGP
"""

#первичный анализ данных с pandas

#https://habr.com/ru/company/ods/blog/322626/#3-demonstratsiya-osnovnyh-metodov-pandas
import pandas as pd

data = pd.read_csv('/content/telecom_churn.csv')

data.head()

data.shape

data.info()

data.describe()

data['Total intl charge']

#loc и iloc

data.loc[0:10, ['Area code', 'Total day charge']]

data.iloc[:,2:4]

data[data['Area code'] == 415]['Account length'].mean(), \
data[data['Area code'] == 510]['Account length'].mean()

data2 = pd.read_csv('/content/test.csv')
data2.info()

data2[data2['Sex'] == 'female']['Pclass'].mean() ,\
data2[data2['Sex'] == 'male']['Pclass'].mean() ,\

data2[(data2['Age'] < 30) & (data2['Sex'] == 'female')]['Pclass'].mean()

data2.groupby('Pclass')

pd.crosstab(data2['Sex'], data2['Pclass'])

pd.crosstab(data['Churn'], data['International plan'], margins=True)

data['Many_service_calls'] = (data['Customer service calls'] > 3).astype('int')

pd.crosstab(data['Many_service_calls'], data['Churn'], margins=True)
